version: '3.8'

services:
    db:
      image: docker.io/postgres
      restart: always
      ports:
        - 6432:5432
      environment:
        - POSTGRES_USER=ctf
        - POSTGRES_PASSWORD=ctf
      networks:
        - db

    adminer:
      image: docker.io/adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - db

networks:
    db:
        driver: bridge
